apiVersion: v1
kind: Pod
metadata:
  name: dind-build
  labels:
    app: dind-build
spec:
  containers:
  - name: docker
    image: docker:24-dind
    command: ["sh", "-c", "dockerd --insecure-registry registry:5000 &>/var/log/dockerd.log & sleep infinity"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-storage
      mountPath: /var/lib/docker
  volumes:
  - name: docker-storage
    emptyDir:
      sizeLimit: 5Gi
